### ISSUE TITLE
Sage Agnostic: checklist

### ISSUE THREAD

**Issue by leopuleo** [leopuleo/roots#4]
Here below the list of themes parts:

- [x] General theme wrapper: base.php
- [ ] Header + nav menu: templates/header.php + lib/nav.php
- [x] Footer: templates/footer.php 
- [ ] Forms: templates/searchform.php + Private page login (New)
- [ ] Alerts: 404.php + base.php + index.php
- [ ] Comments: templates/comment.php
- [ ] Gallery: lib/gallery.php
